-- Execute este script no SQL Editor do projeto Supabase antes de publicar o site.
create table if not exists public.calculos_agua (
  id bigint generated by default as identity primary key,
  nome text not null,
  peso_kg numeric(6,2) not null check (peso_kg > 0),
  quantidade_ml integer not null check (quantidade_ml > 0),
  criado_em timestamptz not null default now()
);

-- Remove a coluna legada caso a tabela já tenha sido criada com e-mail.
alter table public.calculos_agua drop column if exists email;

alter table public.calculos_agua enable row level security;

drop policy if exists "Permitir salvar cálculo de água" on public.calculos_agua;
create policy "Permitir salvar cálculo de água"
  on public.calculos_agua for insert
  to anon
  with check (true);

drop policy if exists "Permitir listar participantes" on public.calculos_agua;
create policy "Permitir listar participantes"
  on public.calculos_agua for select
  to anon
  using (true);
